name: terraform-plan


on:
  workflow_dispatch:  # déclenchement manuel depuis l'onglet Actions

permissions:
  contents: read
  id-token: write  # requis pour OIDC

jobs:
  terraform-plan:
    name: Terraform Init & Plan (manual)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra  # adapte si ton code n'est pas dans infra/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -out=tfplan -input=false
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.run_id }}
          path: infra/plan.txt
